// All Products Type and Array
type Product = {
  path: string;
  id: number;
  name: string;
  category: string;
  type: string;
  price: number;
  brand: string;
  dateAdded: string;
  image: string;
  className?: string;
  description: string;
  specification: string[];
  Dimensions: string[];
};

const products: Product[] = [
  {
    path: "dandy",
    id: 1,
    name: "The Dandy Chair",
    category: "Furniture",
    type: "Chair",
    price: 120,
    brand: "Brand A",
    dateAdded: "2023-12-01",
    image: "/Photo01.png",
    description:
      "The Dandy Chair is crafted with a combination of modern aesthetics and comfort, perfect for any living room or office space. It offers great style, durability, and cozy seating.",
    specification: [
      "Premium material",
      "Handmade upholstery",
      "Quality timeless classic",
    ],
    Dimensions: ["110cm", "75cm", "50cm"],
  },
  {
    path: "rustic",
    id: 2,
    name: "Rustic Vase Set",
    category: "Decor",
    type: "Vase",
    price: 80,
    brand: "Brand B",
    dateAdded: "2023-12-02",
    image: "/Photo02.png",
    description:
      "This Rustic Vase Set adds a charming, earthy touch to your home. The handcrafted design and natural textures make it a beautiful statement piece for your living room or hallway.",
    specification: ["Eco-friendly materials", "Handcrafted", "Natural finish"],
    Dimensions: ["30cm", "15cm", "15cm"],
  },
  {
    path: "silky",
    id: 3,
    name: "The Silky Vase",
    category: "Decor",
    type: "Vase",
    price: 90,
    brand: "Brand C",
    dateAdded: "2023-12-03",
    image: "/Photo03.png",
    description:
      "The Silky Vase brings a touch of elegance and refinement to your decor. Its smooth surface and graceful design make it perfect for displaying flowers or simply enhancing your space.",
    specification: ["Smooth finish", "Elegant design", "Durable ceramic"],
    Dimensions: ["35cm", "18cm", "18cm"],
  },
  {
    path: "lucy",
    id: 4,
    name: "The Lucy Lamp",
    category: "Lighting",
    type: "Lamp",
    price: 150,
    brand: "Brand D",
    dateAdded: "2023-12-04",
    image: "/Photo04.png",
    description:
      "The Lucy Lamp combines modern design with ambient lighting to create a warm, inviting atmosphere. Its versatile style complements a wide range of home decor, from minimalist to traditional.",
    specification: ["Adjustable brightness", "Energy-efficient", "LED light"],
    Dimensions: ["60cm", "25cm", "25cm"],
  },
  {
    path: "coffee-table",
    id: 5,
    name: "Elegant Coffee Table",
    category: "Furniture",
    type: "Table",
    price: 200,
    brand: "Brand A",
    dateAdded: "2023-12-05",
    image: "/Photo05.png",
    description:
      "This Elegant Coffee Table blends modern sophistication with timeless style. Its sleek design and premium construction make it the perfect addition to any living room, offering both function and style.",
    specification: [
      "Tempered glass top",
      "Solid wood frame",
      "Easy to assemble",
    ],
    Dimensions: ["120cm", "60cm", "45cm"],
  },
  {
    path: "armchair",
    id: 6,
    name: "Modern Armchair",
    category: "Furniture",
    type: "Chair",
    price: 250,
    brand: "Brand B",
    dateAdded: "2023-12-06",
    image: "/Photo06.png",
    description:
      "The Modern Armchair features clean lines and superior comfort. It is designed for ultimate relaxation and is a perfect fit for contemporary spaces, adding elegance and a cozy atmosphere to your home.",
    specification: [
      "Ergonomic design",
      "Soft, durable fabric",
      "Solid wood legs",
    ],
    Dimensions: ["90cm", "80cm", "85cm"],
  },
  {
    path: "bookshelf",
    id: 7,
    name: "Classic Bookshelf",
    category: "Furniture",
    type: "Shelf",
    price: 300,
    brand: "Brand C",
    dateAdded: "2023-12-07",
    image: "/Photo07.png",
    description:
      "The Classic Bookshelf is a perfect blend of functionality and style. Its sturdy frame and spacious shelves provide ample storage, making it ideal for organizing books and decorative items in your home.",
    specification: ["Sturdy wooden frame", "Multiple shelves", "Smooth finish"],
    Dimensions: ["180cm", "80cm", "30cm"],
  },
  {
    path: "wall-clock",
    id: 8,
    name: "Artistic Wall Clock",
    category: "Decor",
    type: "Clock",
    price: 75,
    brand: "Brand D",
    dateAdded: "2023-12-08",
    image: "/Photo08.png",
    description:
      "The Artistic Wall Clock features a unique, eye-catching design that adds personality to any room. Its bold numbers and minimalist style make it a stylish and functional timepiece for your home.",
    specification: ["Silent mechanism", "Durable build", "Bold, clear numbers"],
    Dimensions: ["40cm", "40cm", "5cm"],
  },
  {
    path: "floor-lamp",
    id: 9,
    name: "Stylish Floor Lamp",
    category: "Lighting",
    type: "Lamp",
    price: 180,
    brand: "Brand A",
    dateAdded: "2023-12-09",
    image: "/Photo09.png",
    description:
      "The Stylish Floor Lamp offers both beauty and functionality. Its sleek, modern design and adjustable light make it perfect for creating the ideal ambiance in your living room or reading nook.",
    specification: ["Adjustable height", "Energy-saving", "Metallic finish"],
    Dimensions: ["160cm", "30cm", "30cm"],
  },
  {
    path: "sofa",
    id: 10,
    name: "Luxury Sofa",
    category: "Furniture",
    type: "Sofa",
    price: 350,
    brand: "Brand C",
    dateAdded: "2023-12-10",
    image: "/Photo10.png",
    description:
      "This Luxury Sofa offers unparalleled comfort and timeless elegance. It is the perfect addition to any living room, providing both style and coziness.",
    specification: [
      "Premium upholstery material",
      "Durable hardwood frame",
      "Ergonomic design for comfort",
    ],
    Dimensions: ["220cm", "85cm", "95cm"],
  },
  {
    path: "small-clock-table",
    id: 11,
    name: "Small Clock and Table Set",
    category: "Decor",
    type: "Clock & Table",
    price: 120,
    brand: "Brand B",
    dateAdded: "2023-12-11",
    image: "/Photo11.png",
    description:
      "This Small Clock and Table Set adds functionality and charm to compact spaces, perfect for minimalist decor enthusiasts.",
    specification: [
      "Handcrafted wooden table",
      "Quartz clock mechanism",
      "Rustic finish",
    ],
    Dimensions: ["75cm", "175cm", "100cm"],
  },
  {
    path: "sofa-side-table",
    id: 12,
    name: "Sofa with Side Table",
    category: "Furniture",
    type: "Sofa & Table",
    price: 400,
    brand: "Brand A",
    dateAdded: "2023-12-12",
    image: "/Photo12.png",
    description:
      "This elegant sofa and side table combination is perfect for creating a stylish and functional seating area in your home.",
    specification: [
      "High-density foam cushioning",
      "Tempered glass side table",
      "Easy-to-clean upholstery",
    ],
    Dimensions: ["75cm", "175cm", "80cm"],
  },
  {
    path: "sofa-set",
    id: 13,
    name: "Cozy Sofa Set",
    category: "Furniture",
    type: "Sofa Set",
    price: 800,
    brand: "Brand D",
    dateAdded: "2023-12-13",
    image: "/Photo13.png",
    description:
      "This Cozy Sofa Set includes a three-seater, loveseat, and armchair, offering luxurious comfort for the whole family.",
    specification: [
      "Soft-touch fabric",
      "Sturdy wooden legs",
      "Contemporary design",
    ],
    Dimensions: ["110cm", "75cm", "50cm"],
  },
  {
    path: "office-table-chair",
    id: 14,
    name: "Office Table with Chair",
    category: "Furniture",
    type: "Office Furniture",
    price: 450,
    brand: "Brand A",
    dateAdded: "2023-12-14",
    image: "/Photo14.png",
    description:
      "This office table and chair set features an ergonomic design, perfect for enhancing productivity in a modern workspace.",
    specification: [
      "Ergonomic office chair",
      "Scratch-resistant table finish",
      "Adjustable chair height",
    ],
    Dimensions: ["110cm", "75cm", "50cm"],
  },
  {
    path: "modern-chair",
    id: 15,
    name: "Modern Chair",
    category: "Furniture",
    type: "Chair",
    price: 180,
    brand: "Brand B",
    dateAdded: "2023-12-15",
    image: "/Photo15.png",
    description:
      "The Modern Chair combines sleek design with unmatched comfort, perfect for dining or accent seating.",
    specification: [
      "Lightweight yet durable",
      "Smooth curved backrest",
      "Anti-slip feet",
    ],
    Dimensions: ["50cm", "50cm", "100cm"],
  },
  {
    path: "sofa-chair",
    id: 16,
    name: "Comfort Sofa Chair",
    category: "Furniture",
    type: "Chair",
    price: 230,
    brand: "Brand C",
    dateAdded: "2023-12-16",
    image: "/Photo16.png",
    description:
      "This Comfort Sofa Chair is designed for relaxing with extra-wide seating and plush cushions, ideal for your living space.",
    specification: [
      "High-resilience foam",
      "Removable cushion covers",
      "Solid wood frame",
    ],
    Dimensions: ["90cm", "90cm", "100cm"],
  },
  {
    path: "restaurant-set",
    id: 17,
    name: "Restaurant Table and Chair Set",
    category: "Furniture",
    type: "Table & Chair Set",
    price: 700,
    brand: "Brand D",
    dateAdded: "2023-12-17",
    image: "/Photo17.png",
    description:
      "This Restaurant Table and Chair Set features a sleek and durable design, perfect for modern dining spaces.",
    specification: [
      "Weather-resistant materials",
      "Comfortable seating",
      "Compact design for small spaces",
    ],
    Dimensions: ["75", "180cm", "80cm"],
  },
  {
    path: "room-setup",
    id: 18,
    name: "Room Setup with Sofa, Light, and Table",
    category: "Decor",
    type: "Room Setup",
    price: 1500,
    brand: "Brand A",
    dateAdded: "2023-12-18",
    image: "/Photo18.png",
    description:
      "Complete your living room with this all-in-one setup, featuring a cozy sofa, stylish table, and modern lighting.",
    specification: [
      "Coordinated design elements",
      "Adjustable lighting options",
      "Easy-to-maintain materials",
    ],
    Dimensions: ["110cm", "75cm", "50cm"],
  },
  {
    path: "light-decoration",
    id: 19,
    name: "Light and Decoration Set",
    category: "Lighting",
    type: "Decor",
    price: 250,
    brand: "Brand B",
    dateAdded: "2023-12-19",
    image: "/Photo19.png",
    description:
      "This Light and Decoration Set adds a warm ambiance to your space, combining practical lighting with decorative elements.",
    specification: [
      "Energy-efficient LED lighting",
      "Handcrafted decorative pieces",
      "Versatile placement options",
    ],
    Dimensions: ["110cm", "75cm", "50cm"],
  },
  {
    path: "dining-set",
    id: 20,
    name: "Dining Chair and Table Set",
    category: "Furniture",
    type: "Dining Set",
    price: 1000,
    brand: "Brand C",
    dateAdded: "2023-12-20",
    image: "/Photo20.png",
    description:
      "Upgrade your dining room with this elegant dining table and chair set, perfect for family meals and gatherings.",
    specification: [
      "Expandable table feature",
      "Comfortable cushioned chairs",
      "Scratch-resistant finish",
    ],
    Dimensions: ["110cm", "75cm", "50cm"],
  },
  {
    path: "kitchen-set",
    id: 21,
    name: "Kitchen Table and Chair Set",
    category: "Furniture",
    type: "Kitchen Set",
    price: 850,
    brand: "Brand D",
    dateAdded: "2023-12-21",
    image: "/Photo21.png",
    description:
      "The Kitchen Table and Chair Set combines practicality with modern design, ideal for casual dining or meal prep.",
    specification: [
      "Compact, space-saving design",
      "Durable and easy to clean",
      "Minimalist aesthetic",
    ],
    Dimensions: ["110cm", "75cm", "50cm"],
  },
];

export default products;
